const envobj = {
  FB_APIKEY: process.env.REACT_APP_FB_APIKEY,
  FB_AUTHDOMAIN: process.env.REACT_APP_FB_AUTHDOMAIN,
  FB_PROJECTID: process.env.REACT_APP_FB_PROJECTID,
  FB_STORAGEBUCKET: process.env.REACT_APP_FB_STORAGEBUCKET,
  FB_MESSAGINGSENDERID: process.env.REACT_APP_FB_MESSAGINGSENDERID,
  FB_APPID: process.env.REACT_APP_FB_APPID,

  URL_API: process.env.REACT_APP_URL_API,
};

const {
  //fire Bae
  FB_APIKEY,
  FB_AUTHDOMAIN,
  FB_PROJECTID,
  FB_STORAGEBUCKET,
  FB_MESSAGINGSENDERID,
  FB_APPID,

  URL_API,
} = envobj;

console.log({ envobj });

export {
  FB_APIKEY,
  FB_AUTHDOMAIN,
  FB_PROJECTID,
  FB_STORAGEBUCKET,
  FB_MESSAGINGSENDERID,
  FB_APPID,
  URL_API,
};
